### ISSUE TITLE
Setup Angular JS Project Build

### ISSUE THREAD

**Issue by accolasia** [openmastery/ideaflow-profiler#9]
The Idea Flow Map visualizer/editor application will be a JS Angular front-end that talks to a REST backend (ifm-publisher project contains SpringBoot services).

Initially, we just need a boiler plate Angular JS build with a hello world app as the starting point.

The architecture looks like this:
https://github.com/ideaflow/docs/blob/master/ifm_team_mastery_platform.png

**Comment by RAIIST** [comment]
https://github.com/angular/angular-cli
https://www.npmjs.com/package/@angular/material
